import './alg-components/styles/color.js';
import './alg-components/styles/typography.js';
import './styles.js';
import { AlgLog } from './alg-components/alg-log.js';
import { AppController } from './app-controller.js';
import './alg-components/icons/alg-iron-icons.js';
import './alg-components/icons/alg-base64-icons.js';
import { AlgIronIcon } from './alg-components/iron/alg-iron-icon.js';
import { AlgButton } from './alg-components/components/alg-button.js';
import { AlgPaperButton } from './alg-components/paper/alg-paper-button.js';
import { AlgPaperFab } from './alg-components/paper/alg-paper-fab.js';
import { AlgShowLog } from './alg-components/components/alg-show-log.js';
